import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/Layout/header";
import Footer from "./components/Layout/footer";
import AnimatedCursor from "react-animated-cursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pixel2Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <AnimatedCursor
          innerSize={8}
          outerSize={44}
          color="0, 0, 0"
          outerAlpha={0.3}
          innerScale={0.7}
          outerScale={1.6}
          trailingSpeed={8}
          clickables={[
            'a',
            'button',
            '.cursor-pointer',
            'input[type="text"]',
            'input[type="email"]'
          ]}
        />
        {children}
        <Footer />
      </body>
    </html>
  );
}
